# Description:
#   - Running Erda Pipelines on GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Test-Erda-Pipeline@DEV
on:
  push:
    branches:
      - develop

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    name: Run fe-docs@feature/latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Erda Pipeline
        uses: hustcer/erda-pipeline@develop
        with:
          action: 'run'
          pid: 213
          app-id: 7542
          environment: 'DEV'
          app-name: 'Fe-Docs'
          branch: 'feature/latest'
          pipeline: 'pipeline.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERDA_USERNAME: ${{ secrets.ERDA_USERNAME }}
          ERDA_PASSWORD: ${{ secrets.ERDA_PASSWORD }}

  Query-Pipeline:
    # needs: Run-Pipeline
    runs-on: ubuntu-latest
    name: Query fe-docs@feature/latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sleep
        run: sleep 5

      - name: Query Erda Pipeline
        uses: hustcer/erda-pipeline@develop
        with:
          action: 'query'
          pid: 213
          app-id: 7542
          environment: 'DEV'
          app-name: 'Fe-Docs'
          branch: 'feature/latest'
          pipeline: 'pipeline.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERDA_USERNAME: ${{ secrets.ERDA_USERNAME }}
          ERDA_PASSWORD: ${{ secrets.ERDA_PASSWORD }}
