# Description:
#   - Running Erda Pipelines on GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Test-Running-Erda-Pipeline
on:
  push:
    branches:
      - develop

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Run Pipeline
        uses: hustcer/erda-pipeline@develop
        with:
          pid: 213
          app-id: 7542
          app-name: 'Fe-Docs'
          environment: 'DEV'
          branch: 'feature/latest'
          pipeline: 'pipeline.yml'
          description: '前端文档开发环境'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERDA_USERNAME: ${{ secrets.ERDA_USERNAME }}
          ERDA_PASSWORD: ${{ secrets.ERDA_PASSWORD }}
