# Description:
#   - Running Erda Pipelines on GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Test-Erda-Pipeline@TEST
on:
  push:
    branches:
      - develop

jobs:
  Run-Pipeline:
    runs-on: ubuntu-latest
    name: Run fe-docs@develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run Erda Pipeline
        uses: hustcer/erda-pipeline@v1.3
        with:
          action: 'run'
          pid: 213
          app-id: 7542
          app-name: 'Fe-Docs'
          branch: 'develop'
          pipeline: 'pipeline.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERDA_USERNAME: ${{ secrets.ERDA_USERNAME }}
          ERDA_PASSWORD: ${{ secrets.ERDA_PASSWORD }}

  Query-Pipeline:
    needs: Run-Pipeline
    runs-on: ubuntu-latest
    name: Query fe-docs@develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Query Erda Pipeline
        uses: hustcer/erda-pipeline@v1.3
        with:
          action: 'query'
          pid: 213
          app-id: 7542
          app-name: 'Fe-Docs'
          branch: 'develop'
          pipeline: 'pipeline.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERDA_USERNAME: ${{ secrets.ERDA_USERNAME }}
          ERDA_PASSWORD: ${{ secrets.ERDA_PASSWORD }}
